default_agent: strands_agent
agents:
  strands_agent:
    name: strands_agent
    entrypoint: /Users/gunjan/Development/agentic-ai-samples/agentcore-gateway-and-strands-agent/agent/strands_agent.py
    platform: linux/arm64
    container_runtime: none
    source_path: /Users/gunjan/Development/agentic-ai-samples/agentcore-gateway-and-strands-agent/agent
    aws:
      execution_role: arn:aws:iam::409851988807:role/StrandsAgentExecutionRole
      execution_role_auto_create: true
      account: '409851988807'
      region: us-east-1
      ecr_repository: 409851988807.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-strands_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: strands_agent-2v6Dnh917z
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:409851988807:runtime/strands_agent-2v6Dnh917z
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-strands_agent-builder
      execution_role: arn:aws:iam::409851988807:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-6a6a8eb7be
      source_bucket: bedrock-agentcore-codebuild-sources-409851988807-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: strands_agent_mem-04lWw6HG2E
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:409851988807:memory/strands_agent_mem-04lWw6HG2E
      memory_name: strands_agent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: true
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
